site_name: A Talk Near the Future of Python
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
    - scheme: slate
      primary: deep orange
      accent: indigo
  features:
    - navigation.top
    - content.code.annotate

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
