site_name: My Docs
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
    - scheme: slate
      primary: deep orange
      accent: indigo
  features:
    - navigation.top
    - content.code.annotate
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search